-- Init schema for Fiftyville (Postgres)
-- Mirrors the SQLite schema from CS50 Fiftyville pset.

CREATE TABLE crime_scene_reports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year INTEGER,
  month INTEGER,
  day INTEGER,
  street TEXT,
  description TEXT
);

CREATE TABLE interviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  year INTEGER,
  month INTEGER,
  day INTEGER,
  transcript TEXT
);

CREATE TABLE people (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  phone_number TEXT,
  passport_number INTEGER,
  license_plate TEXT
);

CREATE TABLE bank_accounts (
  account_number INTEGER PRIMARY KEY,
  person_id INTEGER REFERENCES people(id),
  creation_year INTEGER
);

CREATE TABLE atm_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_number INTEGER,
  year INTEGER,
  month INTEGER,
  day INTEGER,
  atm_location TEXT,
  transaction_type TEXT,
  amount INTEGER
);

CREATE TABLE airports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  abbreviation TEXT,
  full_name TEXT,
  city TEXT
);

CREATE TABLE flights (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  origin_airport_id INTEGER REFERENCES airports(id),
  destination_airport_id INTEGER REFERENCES airports(id),
  year INTEGER,
  month INTEGER,
  day INTEGER,
  hour INTEGER,
  minute INTEGER
);

CREATE TABLE passengers (
  flight_id INTEGER REFERENCES flights(id),
  passport_number INTEGER,
  seat TEXT
);

CREATE TABLE phone_calls (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caller TEXT,
  receiver TEXT,
  year INTEGER,
  month INTEGER,
  day INTEGER,
  duration INTEGER
);

CREATE TABLE bakery_security_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year INTEGER,
  month INTEGER,
  day INTEGER,
  hour INTEGER,
  minute INTEGER,
  activity TEXT,
  license_plate TEXT
);